config/routes.rb
Rails.application.routes.draw do
  resources :user_groups
  resources :users

  root 'registration#new'

    resources :users
    resources :user_groups do
      resources :memberships
    end

    resources :invites

    get '/signup' => 'registration#new', as: :signup
    post '/signup' => 'registration#create'
    get '/signin' => 'authentication#new', as: :signin
    post '/signin' => 'authentication#create'
    get '/signout' => 'authentication#destroy', as: :signout

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships

  has_many :invites
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]
  as_json include: :users

  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
    @invite = Invite.new
    @user_group = UserGroup.find(params[:id])
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
  end

  # GET /user_groups/1/edit
  def edit
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    @user_group = UserGroup.new(user_group_params)
    respond_to do |format|
      if @user_group.save
        @owner_membership = @user_group.memberships.new()
        @owner_membership.user_group_id = @user_group.id
        @owner_membership.user_id = current_user.id
        @owner_membership.membership_type = "owner"
        if @owner_membership.save
          format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
          format.json { render :show, status: :created, location: @user_group }
        else
          format.html { render :new }
          format.json { render json: @owner_membership.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_groups/1
  # PATCH/PUT /user_groups/1.json
  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: 'User group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.require(:user_group).permit(:name, :hashtag)
    end

    def membership_params
      params.require(:membership).permit(
        :user_group_id,
        :user_id,
        :membership_type
      )
    end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group) do |f| %>
  <% if @user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% @user_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hashtag %><br>
    <%= f.text_field :hashtag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Editing User Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hashtag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_groups.each do |user_group| %>
      <tr>
        <td><%= user_group.name %></td>
        <td><%= user_group.hashtag %></td>
        <td><%= link_to 'Show', user_group %></td>
        <td><%= link_to 'Edit', edit_user_group_path(user_group) %></td>
        <td><%= link_to 'Destroy', user_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User group', new_user_group_path %>

app/views/user_groups/new.html.erb
<h1>New User Group</h1>

<%= render 'form' %>

<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_group.name %>
</p>

<p>
  <strong>Hashtag:</strong>
  <%= @user_group.hashtag %>
</p>

<p>
  <strong>Members <strong>
  <% @user_group.users.each do |user|%>
    <p> <%= user.first_name %></p>
  <% end %>
</p>

<%= form_for @invite , :url => invites_path do |f| %>
    <%= f.hidden_field :user_group_id, :value => @user_group.id %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.submit 'Send' %>
<% end %>

<%= link_to 'Add members to group', user_group_memberships_path(@user_group) %>
<%= link_to 'Edit', edit_user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>