config/routes.rb
Rails.application.routes.draw do
  resources :user_groups
  resources :users

  root 'registration#new'

    resources :users
    resources :user_groups do
      resources :memberships
    end

    resources :invites

    get '/signup' => 'registration#new', as: :signup
    post '/signup' => 'registration#create'
    get '/signin' => 'authentication#new', as: :signin
    post '/signin' => 'authentication#create'
    get '/signout' => 'authentication#destroy', as: :signout

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def create
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path
      else
        @sign_in_error = "Email/password combination is invalid"
        render :new
      end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/views/authentication/new.html.erb
<div class="page-body">
  <h1>Sign In</h1>
  <div class="ui form segment">
    <%= form_tag @user, url: signin_path do |f| %>

      <% if @sign_in_error %>
        <div class="ui error message">
          <%= @sign_in_error %>
        </div>
      <% end %>
      <div class="two fields">
        <div class="field">
          <%= label_tag :email %>
          <div class="field">
            <%= email_field_tag :email %>
          </div>
        </div>
        <div class="field">
          <%= label_tag :password %>
          <div class="field">
            <%= password_field_tag :password %>
          </div>
        </div>
        <div class="field">
          <%= submit_tag "Sign In", id: "signing-user-in-action", class: "ui submit button medium" %>
        </div>
      </div>
      <% end %>
  </div>

</div>